security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
#        FOS\UserBundle\Model\UserInterface: sha512

    providers:
        in_memory:
            memory:
                users:
                    ryan:
                        password: ryanpass
                        roles: 'ROLE_USER'
                    admin:
                        password: kitten
                        roles: 'ROLE_ADMIN'

    firewalls:
        default:
            anonymous: ~
            http_basic: ~

        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            anonymous: ~

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
