services:
#    site.example:
#        class: SiteBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
#    sitebundle.datafixtures.orm.loadpracticeslocations:
#        class: SiteBundle\DataFixtures\ORM\LoadPracticesLocations
#        arguments: [ @doctrine.orm.entity_manager ]