<?php

namespace SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SpecialtiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecialtiesRepository extends EntityRepository
{

	public function getAllSpecialties () {
		$queryBuilder = $this->getEntityManager()->createQueryBuilder();
		$queryBuilder->select([
			"specialty.id",
			"specialty.specialty",
		])
			->from("SiteBundle:Specialties", "specialty")
			->where("specialty.deletedDate IS NULL")
			->orderBy("specialty.specialty", "ASC")
		;
		return $queryBuilder->distinct()->getQuery()->getResult();
	}

}
